spring.application.name=climalert-clima-service
server.port=8080
spring.threads.virtual.enabled=true

weather.api.base-url=https://api.weatherapi.com/v1
weather.api.key = ${WEATHER_API_KEY:2454cfb09d17459a9ae230512260507}
weather.api.ubicacion=Buenos Aires